version: '3'

services:
  gpt-assistant:
    image: gpt-assistant
    container_name: gpt-assistant
    build:
      context: ./gpt-assistant
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./gpt-assistant:/usr/src/app
    # ports:
    #   - "5001:5001"
