version: '3'

services:
  gpt-assistant:
    image: gpt-assistant
    container_name: gpt-assistant
    build:
      context: ./gpt-assistant
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./gpt-assistant:/usr/src/app
    depends_on:
        - db
  db:
    image: postgres:15
    container_name: db
    env_file: .env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
